#pragma once
void test_clear_get_size();
void test_insert_find();
void test_insert_get();
void test_remove();
void test_assignment_operator();
void test_copy_constructor();
void test_print();
void test_get_largest();
void test_get_smallest();
void test_for_each();
void test_word_count();